### ISSUE TITLE
VPN crashing on launch

### ISSUE THREAD

**Issue by marina8888** [ultrahorizon/UH-Enterprise-Docs#4]
---
name: Andriod cannot connect
about: Pressing the connect button on Andriod causes the app to crash.
title: Sad.
labels: bug
relevant parties: @jwsi @AnthonyWharton 

---

**Describe the bug**
After managing profiles using a provided code, connecting to the chosen server, pressing the (large, circular) connect button causes the app displays the "UH Enterprise keeps stopping" notification.

**To Reproduce**
1. Go to manage profiles and type in a valid code given by @jwsi 
2. Choose fast server (same error for stealth server)
3. Press the large connect button, which turns into the disconnect button for half a second
4. See error- UH Enterprise keeps stopping. App doesn't crash, and pressing close app does not actually close the app. 

**Expected behaviour**
I expected to be able to connect.

Please see image below and report logs sent from app.
![ouch](https://user-images.githubusercontent.com/38610356/72205558-e1d21800-34c7-11ea-8f52-02b0bb87e0f8.jpg)

**Application (please complete the following information):**
 - Device: Gallaxy A5 (2017)
 - OS: Andriod 
 - Version 8.0.0

**Additional context**

Its sad. So sad. So very sad.

**Comment by jwsi** [comment]
Ok so this has been confirmed as a Samsung only issue. This will now be investigated and a fix will be deployed soon.

**Comment by AnthonyWharton** [comment]
### Update

Upon further investigation it appears to be affecting devices on <Android 10 (that aren’t in the simulator as I missed this!)

A fix is currently being tested and when validated I shall push it forwards for an update and close the issue.

Thanks for your patience!

**Comment by marina8888** [comment]
@AnthonyWharton My phone is android 8.0.0 (as above) so it might also be Andriod 8 issue? We can also test my device if needed.

**Comment by AnthonyWharton** [comment]
Ok, the fix has been pushed to Google so I'll close this issue now.  Expect the update to appear once it rolls out/propagates on the Google Play Store.

**Comment by AnthonyWharton** [comment]
(Correction/Clarification: It's in review, so expect the update (version 1.1) within the next week - usually only takes a couple of days.)
